### ISSUE TITLE
Missing commands to run client files in README

### ISSUE THREAD

**Issue by DevashishJoshi** [BangBreakfast/Dig-that-Architecture-nyu-CSCI-GA.2965-001-FL22#3]
The README does not contain commands to run the client files and also the supported versions for each of the clients.
Assuming the command for the python client is `python client.py`, this is the error I get when I try to run 2 python clients (and the server is running on 5000 port with params 30 5 8):

On the server side:
`[ERROR] The tunnel is much than 8 blocksResource id #5PHP Notice:  Undefined variable: is_websocket in /mnt/c/Users/Dev/HPS/DigThat/server.php on line 115
PHP Notice:  Trying to access array offset on value of type null in /mnt/c/Users/Dev/HPS/DigThat/server.php on line 115
PHP Notice:  Undefined variable: is_websocket in /mnt/c/Users/Dev/HPS/DigThat/server.php on line 116
PHP Notice:  Trying to access array offset on value of type null in /mnt/c/Users/Dev/HPS/DigThat/server.php on line 116
[LOG] invalid input or timed out`

On the client side:
`Traceback (most recent call last):
  File "client.py", line 189, in <module>
    client.playgame()
  File "client.py", line 80, in playgame
    end_flag = self.send_detector()
  File "client.py", line 55, in send_detector
    raise "If you did not stop the program yourself, please emal lg3405 and cc dw2691\n"
TypeError: exceptions must derive from BaseException`

**Comment by DevashishJoshi** [comment]
Update: I checked the code in the part of the client that creates the tunnel. The length of the tunnel is set to number of grids, which is what caused the issue.
